DROP DATABASE IF EXISTS LINKS;
DROP TABLE IF EXISTS LINKS;

CREATE DATABASE LINKS;

CREATE TABLE LINKS.LINK (
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) PRIMARY KEY NOT NULL,
    link TEXT NOT NULL
) Engine=InnoDB;